Add Lunr Languages Guide
olivernn/lunr-site pull request #2
Opened 2017-08-07 20:00 UTC by olivernn

Sections on installation, multi language support and the current list of supported languages.

cc @MihaiValentin

2017-08-08 07:26 UTC, shamrin requested changes

2017-08-08 07:26 UTC, shamrin commented on source/guides/language_support.html.md
> +$ npm install -g lunr-languages
Are you sure about `-g` flag? I think it makes the installation global (in user home directory).

2017-08-08 07:26 UTC, shamrin commented on source/guides/language_support.html.md
> +If you have documents in more than one language, it is still possible to index them together by combining two or more language extensions using the `lunr.multiLanguage` plugin.
It would be nice to add "(included in `lunr-languages`)". At first I thought`lunr.multiLanguage` is a separate package.

2017-08-08 07:26 UTC, shamrin commented on source/guides/language_support.html.md
> +```
Could you add a simple example on how to use `idx` below? I think people not yet familiar with lunr would do the research, read this page and wonder "ok, I have an index. How do I search it now?".

2017-08-09 08:24 UTC, olivernn commented on source/guides/language_support.html.md
> +$ npm install -g lunr-languages
✅

2017-08-09 08:24 UTC, olivernn commented on source/guides/language_support.html.md
> +```
✅

2017-08-09 08:24 UTC, olivernn commented on source/guides/language_support.html.md
> +If you have documents in more than one language, it is still possible to index them together by combining two or more language extensions using the `lunr.multiLanguage` plugin.
✅

2017-08-09 08:28 UTC, olivernn commented
Made those changes and deployed the site, might have to wait for the change to propagate through the CDN etc.

2017-08-09 08:28 UTC, closed without merging

2017-08-09 10:29 UTC, shamrin commented
Great, thank you! 👍